version: '3'
services:
  main_app:
    build:
      context: ./main_app
    ports:
      - "5002:5000"
    environment:
      - HELPER_APP_URL=http://helper_app:5000

  helper_app:
    build:
      context: ./helper_app
    ports:
      - "5001:5000"
