version: '3'
services:
  main_app:
    build:
      context: ./main_app
    ports:
      - "5002:5000"
    depends_on:
      - helper_app
    networks:
      - my_network

  helper_app:
    build:
      context: ./helper_app
    ports:
      - "5001:5000"
    networks:
      - my_network

networks:
  my_network:
