version: '3'
services:
  main_app:
    build:
      context: ./main_app
    ports:
      - "5002:5000"
    depends_on:
      - helper_app

  helper_app:
    build:
      context: ./helper_app
    ports:
      - "5001:5000"