apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    app: k8s-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: container-webapp
          image: serggurzhy/web_app:latest

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: k8s-web-app-service
spec:
  type: LoadBalancer
  selector:
     app: web
  ports:
    - name: app-listener
      protocol: TCP
      port: 1234
      targetPort: 5000

