apiVersion: v1
kind: Service
metadata:
  name: main-app-clusterip
spec:
  selector:
    app: my-app
    name: main-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
