apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: my-app
spec:
  containers:
    - name: main-app
      image: serggurzhy/web_app:latest
      ports:
        - containerPort: 5000
      env:
        - name: HELPER_APP_URL
          value: "http://localhost:8000"
      volumeMounts:
        - mountPath: /shared-data
          name: app-data
    - name: helper-app
      image: serggurzhy/web-app-helper:latest
      ports:
        - containerPort: 8000
      volumeMounts:
        - mountPath: /shared-data
          name: app-data
  volumes:
    - name: app-data
      emptyDir: {}




#serggurzhy/web_app:latest


#serggurzhy/web-app-helper:latest